// Generated by Wrangler by running `wrangler types`

interface Env {
	attendlyCache: KVNamespace;
	ATTENDLY_SIDE_ID: "66cdfe70a73e317ae059b45c";
	WEBFLOW_ACCESS_TOKEN: "51149ea533aa8fad1ead897a849c6ff02074135106acdcc3b4593bd9c63aea37";
}
